# Generated by Django 5.2.6 on 2025-09-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_diseased', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PetMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_vaccinated_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Reunited', 'Reunited'), ('Lost', 'Lost'), ('Found', 'Found'), ('Adopt', 'Adopt')], default='Pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
