# Generated by Django 5.2.6 on 2025-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pettype_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
